### ISSUE TITLE
License

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [felixSchl/purescript-pipes#3]
It would be nice if you could add a license to this project so that people can use it :tongue:

**Comment by felixSchl** [comment]
I am not into the legal side of things - obviously this is a port and has to honour the license of haskell pipes somehow: https://hackage.haskell.org/package/pipes-4.2.0/src/LICENSE. If you could help me assemble a license file, that would be great. I don't really care about which license we end up with as long as it is open-sourcy and respects the haskell pipes license.
