### ISSUE TITLE
0.10.7 compatibility?

### ISSUE THREAD

**Issue by owickstrom** [felixSchl/purescript-pipes#5]
Haven't had the time to try this directly on `purescript-pipes`, but it seems psc 0.10.7 won't compile purescript-pipes in the Hyper travis build:

```
Error found:
in module Pipes.Prelude
at /home/travis/build/owickstrom/hyper/bower_components/purescript-pipes/src/Pipes/Prelude.purs line 33, column 17 - line 33, column 24
  Conflicting definitions are in scope for value discard from the following modules:
    Prelude
    Pipes
```

Is purescript-pipes not compatible with psc 0.10.7? I could send a PR tonight, if so.

**Comment by dikmax** [comment]
It's a problem with updated Prelude and new function `discard`, which have same name with one from pipes.

**Comment by felixSchl** [comment]
I think @dikmax  is right. I would be happy to merge such a PR
